### ISSUE TITLE
Exact datasets of published paper

### ISSUE THREAD

**Issue by kkalouli** [ishita-dg/ScrambleTests#1]
Hi, 
this is not really an issue but more of a clarification question on the data (so please feel free to move it somewhere more appropriate). Can you please tell me which of the datasets contained in the folder testData/true was used for the **negation** set reported in your paper? I am guessing that _subjv_long_ and _subjv_short_ were included but were also _comp_not_long_ and _comp_not_short_ included or were the latter two part of the "same" set?

Thanks in advance for your help
Katerina

**Comment by ishita-dg** [comment]
Hi Katerina,

The dataset used in the paper is actually in a different branch, specifically in: https://github.com/ishita-dg/ScrambleTests/tree/training-experiment/testData/new
The negation set is in the files therein named "comp_not_short" and "comp_not_long". Hope this is helpful!
The subjv sets on the master branch were not used in the final version of the paper.

Best,
Ishita

**Comment by kkalouli** [comment]
Hi Ishita,

thanks a lot for the reply and for making this data available.

Best
Katerina
