### ISSUE TITLE
Results in table 2 of the paper

### ISSUE THREAD

**Issue by arianhosseini** [ishita-dg/ScrambleTests#3]
Hi,

Are the scores from table 2 of the paper (Table 2: Performance on the Comparisons dataset.) from evaluating the model only on `short` splits (i.e. comp_ml_short, comp_not_short, comp_same_short)?

Or is it an average of both short and long splits? In the [code](https://github.com/ishita-dg/ScrambleTests/blob/52f5a3f6d93d7ce1333ea67c59e606f815539def/experiment.py#L120) is seems that it is only on the `short`.

Thanks

**Comment by ishita-dg** [comment]
Hi, 

The results in Table 2 are on the full dataset, with 14670 examples for each of same / more-less / not sub-types. This includes train + test + valid for both long and short combined.

Hope this helps!
